In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Concepts and Technology of AI/Houseprice.csv")

df

HouseAge  HouseFloor   HouseArea     HousePrice
0         52           2  112.945574  543917.179841
1         93           1  174.312126  817740.124828
2         15           4  125.219577  387992.503019
3         72           4  121.210124  240840.742388
4         61           4   59.221737  277273.386525
..       ...         ...         ...            ...
95        85           1  120.193091  540347.535683
96        80           1   56.078992  222539.252789
97        82           2  211.368074  715211.774907
98        53           4   94.277670  210926.069798
99        24           4  285.114646  988329.950912

[100 rows x 4 columns]

In [3]:
houseage = df['HouseAge'].to_numpy()
houseage

array([ 52,  93,  15,  72,  61,  21,  83,  87,  75,  75,  88, 100,  24,
         3,  22,  53,   2,  88,  30,  38,   2,  64,  60,  21,  33,  76,
        58,  22,  89,  49,  91,  59,  42,  92,  60,  80,  15,  62,  62,
        47,  62,  51,  55,  64,   3,  51,   7,  21,  73,  39,  18,   4,
        89,  60,  14,   9,  90,  53,   2,  84,  92,  60,  71,  44,   8,
        47,  35,  78,  81,  36,  50,   4,   2,   6,  54,   4,  54,  93,
        63,  18,  90,  44,  34,  74,  62, 100,  14,  95,  48,  15,  72,
        78,  87,  62,  40,  85,  80,  82,  53,  24])

In [4]:
housefloor = df['HouseFloor'].to_numpy()
housefloor

array([2, 1, 4, 4, 4, 5, 1, 5, 5, 1, 1, 1, 1, 4, 3, 3, 1, 3, 3, 1, 3, 5,
       2, 2, 1, 4, 1, 4, 2, 1, 5, 3, 4, 3, 3, 1, 3, 5, 3, 1, 5, 2, 3, 1,
       2, 2, 4, 5, 3, 1, 4, 5, 4, 5, 5, 3, 5, 4, 5, 3, 3, 4, 2, 2, 5, 1,
       5, 4, 4, 4, 4, 4, 3, 2, 4, 1, 1, 1, 1, 3, 1, 4, 5, 1, 3, 3, 1, 5,
       1, 3, 2, 4, 3, 1, 4, 1, 1, 2, 4, 4])

In [5]:
housearea = df['HouseArea'].to_numpy()
housearea

array([112.94557396, 174.31212647, 125.21957745, 121.21012359,
        59.22173684, 202.39108349, 175.66975581,  62.86968781,
       119.66161606, 277.06647149, 109.89047267,  86.22371802,
       172.36319007, 296.41261353, 110.51381788, 218.03388685,
       240.40490383, 109.409386  , 232.05408715, 141.94578318,
       208.07645765, 208.38242769, 183.94367102,  72.57244251,
       258.8256239 , 130.19501624,  96.6296276 ,  60.19378539,
       197.7232358 , 219.39109046,  54.14695723, 178.02326457,
       106.6239438 , 211.2931976 ,  93.59160725, 222.73443453,
       146.68383658, 284.18249718,  84.38023604, 135.26658776,
        78.36838031, 281.17340457, 269.33483835, 114.48540693,
       214.99601151, 254.30555005, 188.8002029 , 182.41264459,
       110.46307273,  73.27569195, 274.30393949, 275.10451429,
       208.27536432, 134.75744776, 137.30239365, 231.48891972,
       274.27756499, 271.77160607, 244.96888646, 210.50791154,
        71.03499125,  90.40717852, 274.63854713, 201.60

In [6]:
houseprice = df['HousePrice'].to_numpy()
houseprice

array([ 543917.17984142,  817740.12482771,  387992.50301932,
        240840.74238818,  277273.38652523,  662664.12812989,
        852475.55964824,  298786.83701346,  538040.70198319,
        791378.68966438,  337936.65959035,  382611.94113683,
        506203.44357455,  743244.59111291,  403430.33569623,
       1043108.16601744,  982596.73666629,  397128.89979871,
        528758.78197003,  541984.6137248 , 1033973.60932934,
        497937.99690719,  647917.71919826,  334064.20550363,
       1089540.94675596,  525033.95964725,  391101.58149165,
        183104.97039435,  560696.25994893,  966582.06035172,
        230789.44046813,  813223.66347791,  501167.81565254,
        737515.9067797 ,  321996.36274989,  970892.3448663 ,
        577885.28215608, 1160625.0947274 ,  364007.9919224 ,
        626997.13255948,  230001.15960568,  874058.62161555,
        609107.50841373,  421184.72563993,  452874.35954963,
        858723.58041113,  684254.65720567,  519531.5319317 ,
        409421.91774218,

In [7]:
x0 = np.ones(len(houseage))

x0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
X2 = np.array([x0, houseage, housefloor, housearea]).T

W = np.array([0, 0, 0, 0])

Y2 = np.array(houseprice)

In [9]:
Y2

array([ 543917.17984142,  817740.12482771,  387992.50301932,
        240840.74238818,  277273.38652523,  662664.12812989,
        852475.55964824,  298786.83701346,  538040.70198319,
        791378.68966438,  337936.65959035,  382611.94113683,
        506203.44357455,  743244.59111291,  403430.33569623,
       1043108.16601744,  982596.73666629,  397128.89979871,
        528758.78197003,  541984.6137248 , 1033973.60932934,
        497937.99690719,  647917.71919826,  334064.20550363,
       1089540.94675596,  525033.95964725,  391101.58149165,
        183104.97039435,  560696.25994893,  966582.06035172,
        230789.44046813,  813223.66347791,  501167.81565254,
        737515.9067797 ,  321996.36274989,  970892.3448663 ,
        577885.28215608, 1160625.0947274 ,  364007.9919224 ,
        626997.13255948,  230001.15960568,  874058.62161555,
        609107.50841373,  421184.72563993,  452874.35954963,
        858723.58041113,  684254.65720567,  519531.5319317 ,
        409421.91774218,

In [10]:
X2T = np.array([x0, housefloor, housearea, houseprice]).T

X2T

array([[1.00000000e+00, 2.00000000e+00, 1.12945574e+02, 5.43917180e+05],
       [1.00000000e+00, 1.00000000e+00, 1.74312126e+02, 8.17740125e+05],
       [1.00000000e+00, 4.00000000e+00, 1.25219577e+02, 3.87992503e+05],
       [1.00000000e+00, 4.00000000e+00, 1.21210124e+02, 2.40840742e+05],
       [1.00000000e+00, 4.00000000e+00, 5.92217368e+01, 2.77273387e+05],
       [1.00000000e+00, 5.00000000e+00, 2.02391083e+02, 6.62664128e+05],
       [1.00000000e+00, 1.00000000e+00, 1.75669756e+02, 8.52475560e+05],
       [1.00000000e+00, 5.00000000e+00, 6.28696878e+01, 2.98786837e+05],
       [1.00000000e+00, 5.00000000e+00, 1.19661616e+02, 5.38040702e+05],
       [1.00000000e+00, 1.00000000e+00, 2.77066471e+02, 7.91378690e+05],
       [1.00000000e+00, 1.00000000e+00, 1.09890473e+02, 3.37936660e+05],
       [1.00000000e+00, 1.00000000e+00, 8.62237180e+01, 3.82611941e+05],
       [1.00000000e+00, 1.00000000e+00, 1.72363190e+02, 5.06203444e+05],
       [1.00000000e+00, 4.00000000e+00, 2.96412614e

In [11]:
def cost_function(X, Y, W):
  """ Parameters:
    This function finds the Mean Square Error.
    Input parameters:
      X: Feature Matrix
      Y: Target Matrix
      W: Weight Matrix
    Output Parameters:
      J: accumulated mean square error.
    """

  m = len(Y)

  J = np.sum((X.dot(W) - Y)** 2) / (2 * m)

  return J

In [12]:
# Test case
X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11])
W_test = np.array([1, 1])

cost = cost_function(X_test, Y_test, W_test)


if cost == 0:
    print("Proceed Further")
else:
    print("Something went wrong: Reimplement the cost function")
    print("Cost function output:", cost)

Proceed Further


In [13]:
initial_cost = cost_function(X2, Y2, W)
print(initial_cost)

201528080199.132


In [14]:
def gradient_descent(X, Y, B, alpha, iterations):
    cost_history = [0] * iterations
    m = len(Y)

    for iteration in range(iterations):

        Y_pred = X.dot(B)

        loss = Y_pred - Y

        dw = (X.T.dot(loss) ) / (m)

        W_update = W - alpha * dw

        cost = cost_function(X, Y, W_update)
        cost_history[iteration] = cost

    return W_update, cost_history

In [15]:
alpha = 0.0001
new_weights, cost_history = gradient_descent(X2, Y2, W, alpha, 100000)


print(new_weights)


print(cost_history)

[   57.90964467  2882.43657469   163.66858437 11347.09479342]
[1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 1312493126984.383, 131249

In [16]:
def rmse(Y, Y_pred):
  """
  This Function calculates the Root Mean Squres.
  Input Arguments:
    Y: Array of actual(Target) Dependent Varaibles.
    Y_pred: Array of predeicted Dependent Varaibles.
  Output Arguments:
    rmse: Root Mean Square.
  """
  rmse = np.sqrt(sum((Y-Y_pred)**2)/len(Y))
  return rmse

In [17]:
def r2(Y, Y_pred):
  """
   This Function calculates the R Squared Error.
  Input Arguments:
    Y: Array of actual(Target) Dependent Varaibles.
    Y_pred: Array of predeicted Dependent Varaibles.
  Output Arguments:
    rsquared: R Squared Error.
    """
  mean_y = np.mean(Y)
  ss_tot = sum((Y - mean_y) ** 2)
  ss_res = sum((Y - Y_pred) ** 2)
  r2 = 1 - (ss_res / ss_tot)
  return r2

In [18]:
Y_pred = X2.dot(new_weights)

print(rmse(Y2, Y_pred))
print(r2(Y2, Y_pred))

1620180.9324790756
-37.77181501305387
