Task 1 : Initialize an empty array with size 2X2

In [ ]:
import numpy as np

# Task 1: Initialize an empty array with size 2x2.
a = np.empty((2, 2))
print(a)


[[4.83924057e-310 0.00000000e+000]
 [2.90435030e-144 6.64249506e-310]]


Task 2: Initialize an all one array with size 4X2.

In [ ]:
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Task 3 :Return a new array of given shape and type, filled with fill value.

In [ ]:
filled_array = np.full((3, 3),fill_value= 7)
print(filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


Task 4:Return a new array of zeros with same shape and type as a given array.

In [ ]:
given_array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(given_array)
print("Given Array:")
print(given_array)
print("\nNew Array of Zeros with Same Shape and Type:")
print(zeros_array)

Given Array:
[[1 2]
 [3 4]]

New Array of Zeros with Same Shape and Type:
[[0 0]
 [0 0]]


Task 5: Return a new array of ones with same shape and type as a given array.

In [ ]:
ones_like = np.ones_like(filled_array)
print(ones_like)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Task 6 :For an existing list new_list = [1,2,3,4] convert to an numpy array.

In [ ]:
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


Problem 2 : Array manipulation :Numerical Ranges and Array indexing

Task1 : Create an array with values ranging from 10 to 49.


In [ ]:
array_10_to_49 = np.arange(10, 50)
print(array_10_to_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Task 2 : Create a 3X3 matrix with values ranging from 0 to 8.

In [ ]:
array_0_8 = np.reshape((np.arange(0,9)),(3,3))
print(array_0_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Task 3 : Create a 3X3 identity matrix.

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task4 : Create a random array of size 30 and find the mean of the array.

In [ ]:
random_array = np.random.rand(30)
mean_arr = random_array.mean()
print(mean_arr)

0.5088697666330795


Task 5 :Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_array_1=np.random.rand(10,10)
min_value = random_array_1.min()
max_value = random_array_1.max()
print(min_value)
print(max_value)


0.0011714030924404595
0.9939080193907912


Task 6 : Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Task 7 : Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print( reversed_arr)


[0, 4, 0, 0, 2, 1]


Task 8 : Create a 2d array with 1 on border and 0 inside

In [ ]:
border_array = np.ones((6, 6))
border_array[1:-1, 1:-1] = 0
print(border_array)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


Task 9 : Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3 : Array Operations

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:


1. Add the two array.

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


In [ ]:
sum_xy = x + y
print(sum_xy)

Addition of x and y:
 [[ 6  8]
 [10 13]]


Task 2 : Subtract the two array.

In [ ]:
diff_xy = x - y
print(diff_xy)

[[-4 -4]
 [-4 -3]]


Task 3 : Multiply the array with any integers of your choice

In [ ]:
multiply_x = x * 3
print(multiply_x)

[[ 3  6]
 [ 9 15]]


Task 4 : Find the square of each element of the array.

In [ ]:
square_x = x ** 2
print(square_x)


[[ 1  4]
 [ 9 25]]


Task 5 : Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
dot_prd_vw = np.dot(v, w)
dot_prd_xv = np.dot(x, v)
dot_prd_xy = np.dot(x, y)
print(dot_prd_vw)
print(dot_prd_xv)
print(dot_prd_xy)

219
[29 77]
[[19 22]
 [50 58]]


Task 6 : Concatenate x(and)y along row and Concatenate v(and)w along column.


In [ ]:
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
print(concat_xy_row)
print(concat_vw_col)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


Task 7 : 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print(e)
# Explanation:
# The error occurs because x is a 2D array (shape (2, 2)) and v is a 1D array (shape (2,)).
# To concatenate, both arrays must have the same number of dimensions or compatible shapes.


all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem 4 : Matrix Operations

Task 1 : Prove A.A−1 = I.

In [ ]:
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
result = np.round(result, decimals=10)
print("A * A^(-1):\n", result)


A * A^(-1):
 [[1. 0.]
 [0. 1.]]


Task 2 : Prove AB ̸= BA.

In [ ]:
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


Task 3 : Prove (AB)T = BTAT

In [ ]:
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("Are (AB)^T and B^T * A^T equal? ", np.array_equal(AB_T, BT_AT))

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal?  True


Linear Equation using Inverse Methods

In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X_alt = np.linalg.solve(A, B)
print("Solution using inverse method (X):", X)
print("Solution using np.linalg.solve (X_alt):", X_alt)


Solution using inverse method (X): [ 2.  1. -2.]
Solution using np.linalg.solve (X_alt): [ 2.  1. -2.]
